USE MTBZone;
GO

CREATE TABLE Carts.Items
(
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Title VARCHAR(255),
    Price FLOAT(26),
    Quantity BIGINT,
    CartId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Cart].Carts(Id),
    ExternalId UNIQUEIDENTIFIER
);