CREATE TABLE Orders.Items (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Title VARCHAR(255),
    Price FLOAT(26),
    Quantity BIGINT,
    OrderId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Orders].Orders(Id),
    ExternalId UNIQUEIDENTIFIER
);